application: spuddit
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: django
  version: "1.3"  

env_variables:
  DJANGO_SETTINGS_MODULE: "djangosettings"

handlers:

- url: /styles
  static_dir: styles
  
- url: /Views/bootstrap
  static_dir: Views/bootstrap

- url: /Views/Viewcontrollers
  static_dir: Views/Viewcontrollers
 
- url: /.*
  script: Controllers.corecode.app
